SELECT
    A.AUTHOR_ID, 
    A.AUTHOR_NAME, 
    B.CATEGORY,
    SUM(S.SALES * B.PRICE) AS TOTAL_SALES
FROM 
    (SELECT *
     FROM BOOK_SALES
     WHERE YEAR(SALES_DATE) = '2022' AND MONTH(SALES_DATE) = '1'
    ) AS S
JOIN
    BOOK B ON S.BOOK_ID = B.BOOK_ID
JOIN
    AUTHOR A ON A.AUTHOR_ID = B.AUTHOR_ID
GROUP BY 
    A.AUTHOR_ID, A.AUTHOR_NAME, B.CATEGORY
ORDER BY
    1 ASC, 3 DESC;