-- 조인
-- 년, 월, 성별별로 그룹화
-- 회원수 집계
SELECT
    YEAR(O.SALES_DATE) AS YEAR, 
    MONTH(O.SALES_DATE) AS MONTH, 
    U.GENDER AS GENDER,
    COUNT(DISTINCT(U.USER_ID)) AS USERS
FROM 
    ONLINE_SALE O
JOIN (
    SELECT *  
    FROM USER_INFO
    WHERE GENDER IN (0, 1)) U ON O.USER_ID = U.USER_ID
GROUP BY 
    YEAR, MONTH, U.GENDER
ORDER BY
    1 ASC, 2 ASC, 3 ASC;