-- 2022-04-13 취소되지 않은 CS 진료 예약 내역 조회
SELECT
    A.APNT_NO,
    P.PT_NAME, 
    A.PT_NO, 
    A.MCDP_CD, 
    D.DR_NAME, 
    A.APNT_YMD
FROM 
    APPOINTMENT A
LEFT JOIN
    PATIENT P ON A.PT_NO = P.PT_NO
LEFT JOIN
    DOCTOR D ON A.MDDR_ID = D.DR_ID
WHERE
    A.APNT_YMD LIKE '%2022-04-13%' AND APNT_CNCL_YN = 'N'
ORDER BY
    A.APNT_YMD ASC;
    
    