-- 코드를 입력하세요
WITH RECURSIVE FULL_HOURS AS (
SELECT 0 AS HOUR
    UNION ALL
SELECT HOUR + 1 
FROM FULL_HOURS
WHERE HOUR < 23
)
SELECT 
    H.HOUR, 
    COUNT(A.ANIMAL_ID) AS COUNT
FROM 
    FULL_HOURS H
LEFT JOIN
    ANIMAL_OUTS A ON H.HOUR = HOUR(A.DATETIME)
GROUP BY 
    H.HOUR
ORDER BY
    H.HOUR;