# SELECT 
#     SUM(SCORE) AS SCORE, 
#     B.EMP_NO, 
#     EMP_NAME, 
#     POSITION, 
#     EMAIL
# FROM 
#     HR_EMPLOYEES AS B
# LEFT JOIN 
#     HR_GRADE AS C ON B.EMP_NO = C.EMP_NO
# GROUP BY B.EMP_NO
# ORDER BY 1 DESC
# LIMIT 1;

SELECT
    G.SCORE AS SCORE, 
    E.EMP_NO, 
    E.EMP_NAME, 
    E.POSITION, 
    E.EMAIL
FROM (
    SELECT EMP_NO, SUM(SCORE) AS SCORE
    FROM HR_GRADE
    WHERE YEAR = 2022
    GROUP BY EMP_NO
) G
JOIN
    HR_EMPLOYEES E ON G.EMP_NO = E.EMP_NO
WHERE
    G.SCORE = (
    SELECT MAX(SCORE)
    FROM (
        SELECT SUM(SCORE) AS SCORE
        FROM HR_GRADE
        WHERE YEAR = 2022
        GROUP BY EMP_NO
        ) T
    );