-- 2022년 1월 카테고리 별 도서 판매량, 카테고리, 총 판매량
-- 오름차순 ㅣ 카테고리명
SELECT
    CATEGORY,
    SUM(SALES) AS 'TOTAL_SALES'
FROM 
    BOOK_SALES S
LEFT JOIN
    BOOK B ON S.BOOK_ID = B.BOOK_ID
WHERE
    YEAR(SALES_DATE) = '2022' AND MONTH(SALES_DATE) = '1'
GROUP BY 
    CATEGORY
ORDER BY
    1 ASC;